name: Build and Package Quantum Fractal Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
        override: true

    - name: Cache Rust Build
      uses: actions/cache@v3
      with:
        path: |
          QJulia/src/target
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-rust-

    - name: Build Rust Library
      run: |
        cd QJulia/src
        cargo build --release

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Python Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('QJulia/src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r QJulia/src/requirements.txt

  package:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r QJulia/src/requirements.txt

    - name: Package PyQt5 Application
      run: |
        cd QJulia/src
        pyinstaller --noconfirm --onefile --noconsole ^
                    --add-binary "target/release/QJulia.dll;." ^
                    QJulia.py

    - name: Upload Packaged Application and Rust Library
      uses: actions/upload-artifact@v3
      with:
        name: quantum-fractal-package-${{ github.sha }}
        path: |
          QJulia/src/target/release/QJulia.dll
          QJulia/src/dist/QJulia.exe